name: Generate Snake Game

on:
  schedule:
    # Executa diariamente às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout repository content
        uses: actions/checkout@v3

      # Passo 2: Gerar a animação do jogo da cobrinha
      - name: Generate Snake Game from GitHub contribution graph
        uses: Platane/snk@v2
        with:
          # Formato de saída do gráfico
          github_user_name: ${{ github.repository_owner }}
          output: dist/github-contribution-grid-snake.svg

      # Passo 3: Fazer upload do arquivo gerado
      - name: Push Snake Game to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
